name: Build and Upload Artifact

on:
  push:
    branches:
      - main
    tags:
      # YYYYMMDD
      - "20[0-9][0-9][0-1][0-9][0-3][0-9]*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target:
          [
            x86_64-unknown-linux-gnu,
            x86_64-apple-darwin,
            aarch64-apple-darwin,
            x86_64-pc-windows-msvc,
          ]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary-name: wallet
          - os: macos-latest
            target: x86_64-apple-darwin
            binary-name: wallet
          - os: macos-latest
            target: aarch64-apple-darwin
            binary-name: wallet
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary-name: wallet.exe
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install target
        run: rustup target add ${{ matrix.target }}

      - name: Build Release
        run: cargo build --release --target ${{ matrix.target }}

      - name: Release Artifact
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: target/${{ matrix.target }}/release/${{ matrix.binary-name }}
