name: Build and Upload Artifact

on:
  push:
    branches:
      - main
    tags:
      # YYYYMMDD
      - "20[0-9][0-9][0-1][0-9][0-3][0-9]*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary-name: wallet
          - os: macos-latest
            target: x86_64-apple-darwin
            binary-name: wallet
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary-name: wallet.exe
    steps:
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
            version: nightly-2cb875799419c907cc3709e586ece2559e6b340e # Not using the default version because likely of this bug https://github.com/foundry-rs/foundry/issues/7120

      - name: Install just command runner
        run: |
          sudo snap install --edge --classic just
          just --version

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build Release
        run: cargo build --release --target ${{ matrix.target }}

      - name: Release Artifact
        uses: softprops/action-gh-release@v2
        with:
          files: target/nix/${{ matrix.target }}/release/${{ matrix.binary-name }}
